Merge r118947: -- Author: Nick Lewycky <nicholas@mxc.ca> Date:   Fri Nov 12 23:52:43 2010 +0000
    Use dyn_cast result instead of re-casting. Fixes -Werror build with:
    /llvm/tools/clang/tools/libclang/CIndex.cpp:1823: error: unused variable 'E' [-Wunused-variable]